services:
  app:
    image: xream/script-hub:latest
    restart: always
    environment:
      - PORT=9100
      - BASE_URL=http://10.0.0.160:9100
      # - BETA_PORT=9101
      # - BETA_BASE_URL=http://10.0.0.230:9101
    ports:
      - "0.0.0.0:9100:9100"  # 主机上的 9100 端口映射到容器的 PORT
      # - "0.0.0.0:9101:9101"  # 主机上的 9101 端口映射到容器的 BETA_PORT